export const initialCalculatorState = {
  displayResult: false,
  yearsOfMortgage: '10',
  yearsOfMortgageMin: '1',
  yearsOfMortgageMax: '40',
  yearsOfMortgageStep: '1',
  yearsOfMortgageError: '',
  interestRate: '3',
  interestRateMin: '0.1',
  interestRateMax: '10',
  interestRateStep: '0.1',
  interestRateError: '',
  loanAmount: '',
  loanAmountError: '',
  annualTax: '',
  annualTaxError: '',
  annualInsurance: '',
  annualInsuranceError: '',
  principalAndInterest: '$ - -',
  tax: '$ - -',
  insurance: '$ - -',
  monthlyPayment: '$ - -',
};
